[package]
name = "simple-icons-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
env_logger = "0.11.8"
flate2 = "1.1.2"
log = "0.4.27"
once_cell = "1.21.3"
phf = { version = "0.12.1", features = ["macros"] }
regex = "1.11.1"
reqwest = { version = "0.12.23", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.142", features = ["std"] }
tar = "0.4.44"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
unicode-normalization = "0.1.24"
